### ISSUE TITLE
Add Light and Dark mode option

### ISSUE THREAD

**Issue by rko0211** [CSI-DMCE-2024/Note-App-Hacktoberfest2024#18]

**Comment by Shivansh-0403** [comment]
I have done certain work related to this issue locally. Please assign me this issue, so that I can make a PR.
Work done: Modified the Navbar to add a toggle button to switch between different theme modes. Along with that, added Bootstrap CSS for both light and dark modes in each component.

Screenshots
![image](https://github.com/user-attachments/assets/a80b0337-886a-4b2f-8634-1206a4a521cb)
![image](https://github.com/user-attachments/assets/1125d075-766b-4047-b537-77b308bfb00c)
![image](https://github.com/user-attachments/assets/e0f76451-02d5-4550-9a5f-4c9258ea5cc2)
